"""A pasted job description, turned into a People Data Labs query.

**This is the one place in the project where an LLM belongs.** Module A's agent
config is generated by deterministic templating, because a requisition is
structured input: fields, a list of criteria, a list of variables. A job
description is not. It is prose written by a hiring manager, and pulling
"Instrumentation Engineer, Pune, 4+ years" out of three paragraphs is exactly the
job a model does better than a regex.

The generated query is returned, stored and shown before it runs. The recruiter
edits it and the edited version is what executes — so the model proposes and a
person decides, which matters when the alternative is spending metered search
credits on whatever the model guessed.

The fallback is not a stub. Gemini being unavailable must not take the feature
down, so a keyword extractor produces a usable query and the response says
plainly that it did.
"""

import asyncio
import json
import logging
import re
from dataclasses import dataclass
from typing import Any

import httpx

from app.config import settings

logger = logging.getLogger(__name__)

# `gemini-flash-latest`, not a pinned version. Written against
# `gemini-2.0-flash` first, which returned 404 on this key: the version had been
# retired. A pinned model here is a feature that silently degrades to the
# keyword fallback months later, and the only symptom is a slightly worse query.
# The alias moves with Google's deprecations, which is the right trade for a
# prompt that returns strict JSON and is not sensitive to model version.
GEMINI_MODEL = "gemini-flash-latest"
GEMINI_URL = (
    f"https://generativelanguage.googleapis.com/v1beta/models/"
    f"{GEMINI_MODEL}:generateContent"
)
TIMEOUT_SECONDS = 20.0

# Titles worth recognising without a model. Not a taxonomy — just enough that the
# fallback produces a query a recruiter would recognise as related to their JD.
_TITLE_WORDS = (
    "engineer", "developer", "technician", "supervisor", "manager", "analyst",
    "designer", "operator", "inspector", "architect", "consultant", "lead",
)

_INDIAN_CITIES = (
    "bengaluru", "bangalore", "mumbai", "delhi", "pune", "hyderabad", "chennai",
    "kolkata", "ahmedabad", "vadodara", "nagpur", "jaipur", "coimbatore",
    "surat", "noida", "gurugram", "gurgaon",
)

PROMPT = """You convert job descriptions into People Data Labs person-search queries.

Return ONLY a JSON object, no prose and no markdown fence, in this exact shape:

{{"query": {{"bool": {{"must": [ ... ]}}}}, "titles": ["..."], "locations": ["..."]}}

Rules:
- Use only these PDL fields: job_title, job_title_role, job_company_name,
  location_country, location_locality, skills, job_title_levels.
- Prefer a small number of broad clauses. An over-specific query returns nothing
  and still costs credits.
- location_country must be a lowercase country name, for example "india".
- Do not invent seniority or skills that the description does not mention.

Job description:
{jd}"""


@dataclass
class GeneratedQuery:
    query: dict[str, Any]
    titles: list[str]
    locations: list[str]
    source: str          # "gemini" or "fallback"
    note: str


async def jd_to_query(jd_text: str) -> GeneratedQuery:
    if not jd_text.strip():
        raise ValueError("the job description is empty")

    if settings.gemini_api_key:
        try:
            return await _from_gemini(jd_text)
        except Exception as exc:  # noqa: BLE001 - any failure falls back
            # Deliberately broad. Every failure mode here — network, quota,
            # malformed JSON, a schema change — has the same correct response,
            # which is to produce a usable query anyway rather than 500.
            logger.warning("Gemini query generation failed, falling back: %s", exc)
            return _fallback(jd_text, reason=str(exc))

    return _fallback(jd_text, reason="GEMINI_API_KEY is not set")


async def _from_gemini(jd_text: str) -> GeneratedQuery:
    body = {
        "contents": [{"parts": [{"text": PROMPT.format(jd=jd_text[:6000])}]}],
        # Zero temperature: the same JD should produce the same query, or the
        # stored `generated_query` row stops being evidence of anything.
        "generationConfig": {"temperature": 0, "responseMimeType": "application/json"},
    }

    async with httpx.AsyncClient(timeout=httpx.Timeout(TIMEOUT_SECONDS)) as client:
        response = await client.post(
            GEMINI_URL, headers={"x-goog-api-key": settings.gemini_api_key}, json=body
        )
        # One retry, only on 5xx. Observed a 503 on the first live call that
        # succeeded immediately afterwards — the endpoint sheds load. Without
        # this a transient blip silently downgrades the feature to keyword
        # extraction, and the only symptom is a slightly worse query. A 4xx is
        # not retried: a bad key or a retired model fails the same way twice.
        if response.status_code >= 500:
            await asyncio.sleep(1.0)
            response = await client.post(
                GEMINI_URL, headers={"x-goog-api-key": settings.gemini_api_key}, json=body
            )
    response.raise_for_status()

    text = response.json()["candidates"][0]["content"]["parts"][0]["text"]
    parsed = json.loads(_strip_fence(text))
    query = parsed.get("query")
    if not isinstance(query, dict) or not query:
        raise ValueError("Gemini returned no query object")

    return GeneratedQuery(
        query=query,
        titles=[t for t in parsed.get("titles", []) if isinstance(t, str)],
        locations=[l for l in parsed.get("locations", []) if isinstance(l, str)],
        source="gemini",
        note="Generated by Gemini from the job description. Edit it before running the search.",
    )


def _strip_fence(text: str) -> str:
    """Models fence JSON even when told not to."""
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```[a-z]*\n?", "", cleaned)
        cleaned = re.sub(r"\n?```$", "", cleaned)
    return cleaned.strip()


def _fallback(jd_text: str, reason: str) -> GeneratedQuery:
    """Obvious title and location terms, and honesty about what produced them.

    Says it is a fallback in the response rather than quietly returning a worse
    query. A recruiter who thinks a model read their JD will trust the result
    more than it deserves.
    """
    lowered = jd_text.lower()
    titles = _extract_titles(jd_text)
    locations = [c for c in _INDIAN_CITIES if re.search(rf"\b{c}\b", lowered)]

    must: list[dict[str, Any]] = []
    if titles:
        must.append({"bool": {"should": [{"match": {"job_title": t}} for t in titles]}})
    if locations:
        must.append(
            {"bool": {"should": [{"term": {"location_locality": l}} for l in locations]}}
        )
    must.append({"term": {"location_country": "india"}})

    return GeneratedQuery(
        query={"bool": {"must": must}},
        titles=titles,
        locations=locations,
        source="fallback",
        note=(
            f"Built without a model ({reason}). Keyword extraction only: it found "
            f"{len(titles)} title term(s) and {len(locations)} location(s). Check it "
            "before running the search."
        ),
    )


def _extract_titles(jd_text: str) -> list[str]:
    """Capitalised phrases ending in a known role word, plus bare role words.

    "Senior Instrumentation Engineer" is found by the first rule; a JD written
    entirely in lower case still yields "engineer" from the second.
    """
    titles: list[str] = []
    for match in re.finditer(
        r"\b((?:[A-Z][a-z]+[ /-]){0,3}(?:" + "|".join(_TITLE_WORDS) + r"))\b",
        jd_text,
        flags=re.IGNORECASE,
    ):
        phrase = " ".join(match.group(1).split()).strip()
        if phrase.lower() not in {t.lower() for t in titles}:
            titles.append(phrase)
    return titles[:4]
