"""candidate intake status

Revision ID: 106966b2c5b7
Revises: b86f69a40152
Create Date: 2026-09-05 13:47:06.583417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106966b2c5b7'
down_revision: Union[str, Sequence[str], None] = 'b86f69a40152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the NOT NULL is satisfiable on a table that already has
    # rows, then dropped so new inserts must state a status.
    op.add_column(
        'candidates',
        sa.Column(
            'status',
            sa.Enum('NEW', 'DO_NOT_CALL', name='candidatestatus', native_enum=False, length=32),
            nullable=False,
            server_default='NEW',
        ),
    )
    op.alter_column('candidates', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'status')
    # ### end Alembic commands ###
