"""requisition kind

Revision ID: 56f806ca3e0d
Revises: 8b5e0a339cdb
Create Date: 2026-09-05 15:55:06.192971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f806ca3e0d'
down_revision: Union[str, Sequence[str], None] = '8b5e0a339cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('kind', sa.Enum('SCREENING', 'SOURCING', name='requisitionkind', native_enum=False, length=32), server_default='SCREENING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisitions', 'kind')
    # ### end Alembic commands ###
