"""call timing fields and event processing error

Revision ID: a7b0b6537ea3
Revises: d817f547f297
Create Date: 2026-09-05 03:06:25.619452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b0b6537ea3'
down_revision: Union[str, Sequence[str], None] = 'd817f547f297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_events', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('calls', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'ended_at')
    op.drop_column('calls', 'started_at')
    op.drop_column('calls', 'duration_seconds')
    op.drop_column('call_events', 'processing_error')
    # ### end Alembic commands ###
