"""requisition criteria and agent readback variables

Revision ID: b86f69a40152
Revises: bac3f32ca100
Create Date: 2026-09-05 12:40:21.122577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b86f69a40152'
down_revision: Union[str, Sequence[str], None] = 'bac3f32ca100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default on each add so the NOT NULL is satisfiable on a table
    # that already has rows, then dropped so new inserts must supply a value.
    op.add_column('agent_versions', sa.Column('custom_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    op.add_column('agent_versions', sa.Column('required_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    op.add_column('agent_versions', sa.Column('result_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    op.add_column('requisitions', sa.Column('language', sa.String(length=32), nullable=False, server_default='ENGLISH'))
    op.add_column('requisitions', sa.Column('voice_persona', sa.String(length=32), nullable=False, server_default='NEHA'))
    op.add_column('requisitions', sa.Column('criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    op.add_column('requisitions', sa.Column('candidate_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))
    op.drop_column('requisitions', 'knockout_questions')
    op.drop_column('requisitions', 'languages')
    op.drop_column('requisitions', 'rubric')
    op.alter_column('agent_versions', 'custom_variables', server_default=None)
    op.alter_column('agent_versions', 'required_variables', server_default=None)
    op.alter_column('agent_versions', 'result_variables', server_default=None)
    op.alter_column('requisitions', 'language', server_default=None)
    op.alter_column('requisitions', 'voice_persona', server_default=None)
    op.alter_column('requisitions', 'criteria', server_default=None)
    op.alter_column('requisitions', 'candidate_variables', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('requisitions', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('requisitions', sa.Column('knockout_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('requisitions', 'candidate_variables')
    op.drop_column('requisitions', 'criteria')
    op.drop_column('requisitions', 'voice_persona')
    op.drop_column('requisitions', 'language')
    op.drop_column('agent_versions', 'result_variables')
    op.drop_column('agent_versions', 'required_variables')
    op.drop_column('agent_versions', 'custom_variables')
    # ### end Alembic commands ###
