"""reconciliation bookkeeping on calls

Revision ID: bac3f32ca100
Revises: a7b0b6537ea3
Create Date: 2026-09-05 12:22:49.546407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac3f32ca100'
down_revision: Union[str, Sequence[str], None] = 'a7b0b6537ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('reconcile_stopped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('reconcile_stopped_reason', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'reconcile_stopped_reason')
    op.drop_column('calls', 'reconcile_stopped_at')
    op.drop_column('calls', 'last_reconciled_at')
    # ### end Alembic commands ###
