"""webhook events: nullable call id, raw body text

Revision ID: d817f547f297
Revises: f773d9b56c3b
Create Date: 2026-09-05 02:34:30.584425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd817f547f297'
down_revision: Union[str, Sequence[str], None] = 'f773d9b56c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Added with a server_default so the NOT NULL is satisfiable on a table that
    # already has rows, then dropped so new inserts must supply the body.
    op.add_column(
        'call_events',
        sa.Column('raw_body', sa.Text(), nullable=False, server_default=''),
    )
    op.alter_column('call_events', 'raw_body', server_default=None)
    op.alter_column('call_events', 'hunar_call_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('call_events', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_events', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('call_events', 'hunar_call_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('call_events', 'raw_body')
    # ### end Alembic commands ###
