"""campaign dispatch tracking

Revision ID: dc6c068f9c19
Revises: 106966b2c5b7
Create Date: 2026-09-05 14:01:34.750223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6c068f9c19'
down_revision: Union[str, Sequence[str], None] = '106966b2c5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('dispatch_error', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('dispatch_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'dispatch_error')
    op.drop_column('campaigns', 'dispatched_at')
    op.drop_column('calls', 'dispatch_error')
    # ### end Alembic commands ###
