"""initial schema

Revision ID: f773d9b56c3b
Revises: 
Create Date: 2026-09-05 00:45:59.740019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f773d9b56c3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnc_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shift', sa.String(length=120), nullable=True),
    sa.Column('pay_min', sa.Integer(), nullable=True),
    sa.Column('pay_max', sa.Integer(), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('knockout_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcing_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('generated_query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('voice_persona', sa.String(length=32), nullable=False),
    sa.Column('persona_name', sa.String(length=64), nullable=False),
    sa.Column('agent_prompt', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('result_prompt', sa.Text(), nullable=False),
    sa.Column('result_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hunar_agent_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hunar_agent_id'),
    sa.UniqueConstraint('requisition_id', 'version')
    )
    op.create_index(op.f('ix_agent_versions_requisition_id'), 'agent_versions', ['requisition_id'], unique=False)
    op.create_table('interview_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_slots_requisition_id'), 'interview_slots', ['requisition_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SCREENING', 'SOURCING', name='campaignkind', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('agent_version_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('max_retry_count', sa.Integer(), nullable=True),
    sa.Column('retry_interval_hours', sa.Integer(), nullable=True),
    sa.Column('allowed_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('earliest_call_time', sa.String(length=5), nullable=True),
    sa.Column('last_call_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('from_phone_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DISPATCHING', 'RUNNING', 'COMPLETED', 'FAILED', name='campaignstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_campaigns_agent_version_id'), 'campaigns', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_campaigns_requisition_id'), 'campaigns', ['requisition_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('sourcing_search_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('INBOUND_CSV', 'SOURCED_PDL', 'MANUAL', name='candidatesource', native_enum=False, length=32), nullable=False),
    sa.Column('phone_source', sa.String(length=32), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('interview_slot_id', sa.Integer(), nullable=True),
    sa.Column('interview_status', sa.Enum('BOOKED', 'RESCHEDULED', 'ATTENDED', 'NO_SHOW', name='interviewstatus', native_enum=False, length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_slot_id'], ['interview_slots.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['sourcing_search_id'], ['sourcing_searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_candidates_interview_slot_id'), 'candidates', ['interview_slot_id'], unique=False)
    op.create_index(op.f('ix_candidates_requisition_id'), 'candidates', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_candidates_sourcing_search_id'), 'candidates', ['sourcing_search_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('hunar_call_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=True),
    sa.Column('engagement_status', sa.String(length=32), nullable=True),
    sa.Column('answered_by', sa.String(length=32), nullable=True),
    sa.Column('call_ended_by', sa.String(length=32), nullable=True),
    sa.Column('redial_status', sa.String(length=32), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retries_left', sa.Integer(), nullable=True),
    sa.Column('next_retry_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_speech_duration', sa.Float(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.Enum('QUALIFIED', 'REJECTED', 'UNDECIDED', name='screeningdecision', native_enum=False, length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('override_decision', sa.Enum('QUALIFIED', 'REJECTED', 'UNDECIDED', name='screeningdecision', native_enum=False, length=32), nullable=True),
    sa.Column('override_reason_code', sa.String(length=64), nullable=True),
    sa.Column('override_note', sa.Text(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hunar_call_id')
    )
    op.create_index(op.f('ix_calls_campaign_id'), 'calls', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_calls_candidate_id'), 'calls', ['candidate_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('LOGGED', 'WHATSAPP', name='messagechannel', native_enum=False, length=32), nullable=False),
    sa.Column('recipient', sa.String(length=20), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_event', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='messagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_candidate_id'), 'messages', ['candidate_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunar_call_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_hash')
    )
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_events_hunar_call_id'), 'call_events', ['hunar_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_events_hunar_call_id'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_messages_candidate_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_calls_candidate_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_campaign_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_candidates_sourcing_search_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_requisition_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_interview_slot_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_campaigns_requisition_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_agent_version_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_interview_slots_requisition_id'), table_name='interview_slots')
    op.drop_table('interview_slots')
    op.drop_index(op.f('ix_agent_versions_requisition_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_table('sourcing_searches')
    op.drop_table('requisitions')
    op.drop_table('dnc_list')
    # ### end Alembic commands ###
